[build]
builder = "nixpacks"
buildCommand = "cd Server && dotnet restore && dotnet publish -c Release -o out"

[deploy]
startCommand = "cd Server/out && dotnet Server.dll"
restartPolicyType = "always"